title: Jay's Tech Blog
url: 'https://claudebaek.github.io'
paginate: '1'
baseurl: ''
permalink: pretty
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
sass:
  sass_dir: _sass
  style: ':compressed'
author:
  name: Jay
  url: ''
  email: 'appleofeyes0321@gmail.com'
version: 3.0.0
nav:
  - title: CS 
    url: /category/cs
  - title: SwiftTech
    url: /category/swift_tech
  - title: SwiftLecture
    url: /category/swift_lecture
  - title: Business
    url: /category/business

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
